STRUCTURED_HOME = ../../..

# Executable name
tbase = testIntVect testBox testBaseFab testBoxIterator testDisjointBoxLayout \
	testLayoutIterator testLevelData
tmpibase = testMPI testMPIExchange testMPISplitExchange

# Base directory
base_dir = .

# Other directories with required source code
src_dirs = 

# Libraries
libnames = BoxFramework

include $(STRUCTURED_HOME)/Common/mk/Make.example
