STRUCTURED_HOME = ../../..

# Library name
lbase = BoxFramework

# Base directory
base_dir = .

# Other directories with required source code
src_dirs = 

include $(STRUCTURED_HOME)/Common/mk/Make.example
