STRUCTURED_HOME = ../..

# Executable name
ebase = sandbox

# Base directory
base_dir = .

# Other directories with required source code
src_dirs =

# Libraries
libnames = BoxFramework

include $(STRUCTURED_HOME)/Common/mk/Make.example
